"""Stage 5 shim-server + launcher generator.

Ported from the proven logic in D:\\search\\webdow\\serve_sarang.py
(optimizer + api + sw stubs), D:\\search\\webdow\\serve_arif.py
(extensionless routes, http-URL basename lookup, icon shims) and
D:\\search\\webdow\\abeto-clone\\serve.py (wasm/drc MIME, no-store).

Public API used by sibling stages:
    write_server(outdir, routes, api_payloads, port) -> str
    write_launcher(outdir, port) -> str
"""

import json
import os
import re

DEFAULT_PORT = 8919

# ---------------------------------------------------------------------------
# Generated server template. Tokens __NAME__ / __PORT__ / __ROUTES__ /
# __PAYLOADS_JSON__ are replaced verbatim; everything else is literal code
# so no brace-escaping is needed. The generated file is stdlib-only.
# ---------------------------------------------------------------------------
_SERVER_TEMPLATE = '''"""Offline shim server for __NAME__ (generated by siteclone.serve — stage 5)."""
import functools
import json
import mimetypes
import os
import re
import sys
import urllib.parse
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

ROOT = Path(__file__).resolve().parent
NAME = "__NAME__"
DEFAULT_PORT = __PORT__
ROUTES = __ROUTES__
API_PAYLOADS = json.loads(__PAYLOADS_JSON__)

_EXTRA_MIME = {
    ".wasm": "application/wasm",
    ".drc": "application/octet-stream",
    ".glb": "model/gltf-binary",
    ".ktx2": "image/ktx2",
    ".webm": "video/webm",
    ".mjs": "text/javascript",
    ".mp4": "video/mp4",
    ".woff2": "font/woff2",
    ".ogg": "audio/ogg",
}
for _ext, _ct in _EXTRA_MIME.items():
    mimetypes.add_type(_ct, _ext)

# Analytics / tag-manager / service-worker noise answered with empty 200s.
_STUB_SUBSTRINGS = (
    "googletagmanager",
    "googletagservices",
    "gtag/js",
    "google-analytics",
    "googleadservices",
    "doubleclick",
    "fbevents.js",
    "hotjar",
    "mixpanel",
    "segment.io",
    "fullstory",
    "analytics.js",
    "_vercel/insights",
    "cdn-cgi",
    "sw.js",
)

_BEACON_RE = re.compile(r"^/[0-9a-f]{8,}/script\\.js$")

# Basename -> local file index (built once) so optimizer URLs that carry an
# absolute http(s) source can be resolved to whatever local copy was saved.
_BASENAME_INDEX = {}


def _build_index():
    try:
        for p in ROOT.rglob("*"):
            if p.is_file():
                _BASENAME_INDEX.setdefault(p.name.lower(), p)
    except OSError:
        pass


_build_index()


class Handler(SimpleHTTPRequestHandler):
    extensions_map = {
        **SimpleHTTPRequestHandler.extensions_map,
        ".js": "text/javascript",
        ".mjs": "text/javascript",
        ".wasm": "application/wasm",
        ".drc": "application/octet-stream",
        ".glb": "model/gltf-binary",
        ".ktx2": "image/ktx2",
        ".webm": "video/webm",
        ".woff2": "font/woff2",
        ".mp4": "video/mp4",
        ".ogg": "audio/ogg",
    }

    def end_headers(self):
        self.send_header("Cache-Control", "no-store")
        super().end_headers()

    def log_message(self, *a):
        pass

    # -- low-level senders ---------------------------------------------
    def _send_bytes(self, body, ctype):
        if isinstance(body, str):
            body = body.encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    def _send_json(self, obj):
        self._send_bytes(json.dumps(obj, ensure_ascii=False).encode("utf-8"),
                         "application/json")

    def _serve_path(self, local):
        rel = os.path.relpath(str(local), str(ROOT)).replace("\\\\", "/")
        self.path = "/" + rel
        return super().do_GET()

    # -- matchers --------------------------------------------------------
    def _is_stub(self, path):
        lp = path.lower()
        if lp == "/sw.js" or lp.endswith("/sw.js"):
            return True
        if _BEACON_RE.match(lp.split("?", 1)[0]):
            return True  # deploy-hash telemetry beacons (aa1178../script.js)
        return any(s in lp for s in _STUB_SUBSTRINGS)

    def _handle_api(self):
        """GET -> captured payload (or {}); POST -> 200 {}. True if handled."""
        u = urllib.parse.urlsplit(self.path)
        p = u.path
        if not p.startswith("/api/"):
            return False
        if self.command == "POST":
            try:
                length = int(self.headers.get("Content-Length", 0) or 0)
            except (TypeError, ValueError):
                length = 0
            if length:
                self.rfile.read(length)
            self._send_json({})
            return True
        payload = API_PAYLOADS.get(p)
        if payload is None:
            payload = API_PAYLOADS.get(p.rstrip("/"))
        if payload is None:
            payload = {}
        if isinstance(payload, str):
            self._send_bytes(payload, "application/json")
        else:
            self._send_json(payload)
        return True

    def _handle_optimizer(self):
        """/_next/image?url=... -> local file. True if handled."""
        u = urllib.parse.urlsplit(self.path)
        if u.path != "/_next/image":
            return False
        q = urllib.parse.parse_qs(u.query)
        if "url" not in q or not q["url"]:
            return False
        src = urllib.parse.unquote(q["url"][0]).split("?")[0].split("#")[0]
        if src.startswith(("http://", "https://", "//")):
            bn = urllib.parse.unquote(src.rstrip("/").split("/")[-1]) or "index.html"
            hit = _BASENAME_INDEX.get(bn.lower())
            if hit is not None and hit.is_file():
                self._serve_path(hit)
                return True
            self.send_error(404)
            return True
        rel = re.sub(r"^[A-Za-z]:", "", src).lstrip("/")
        cand = ROOT / rel
        if rel and cand.is_file():
            self._serve_path(cand)
            return True
        bn = rel.split("/")[-1] if rel else ""
        hit = _BASENAME_INDEX.get(bn.lower()) if bn else None
        if hit is not None and hit.is_file():
            self._serve_path(hit)
            return True
        self.send_error(404)
        return True

    def _map_route(self, path):
        """Extensionless route -> local .html file (or None for static)."""
        rel = urllib.parse.unquote(path.split("?")[0].split("#")[0]).strip("/")
        rel = re.sub(r"^[A-Za-z]:", "", rel).lstrip("/")
        if not rel:
            cand = ROOT / "index.html"
            return cand if cand.is_file() else None
        if "." in rel.split("/")[-1]:
            return None
        full = ROOT / rel
        if full.is_dir():
            for fname in ("index.html", full.name + ".html"):
                cand = full / fname
                if cand.is_file():
                    return cand
            return None
        cand = ROOT / (rel + ".html")
        if cand.is_file():
            return cand
        idx = ROOT / rel / "index.html"
        if idx.is_file():
            return idx
        return None

    # -- verbs -------------------------------------------------------------
    def do_GET(self):
        u = urllib.parse.urlsplit(self.path)
        p = u.path
        if self._is_stub(p):
            self._send_bytes(b"", "application/javascript")
            return
        if p == "/favicon.ico":
            for cand in (ROOT / "favicon.ico", ROOT / "photo" / "favicon.png",
                         ROOT / "icon.png", ROOT / "apple-icon.png"):
                if cand.is_file():
                    self._serve_path(cand)
                    return
            self._send_bytes(b"", "image/x-icon")
            return
        if self._handle_optimizer():
            return
        if self._handle_api():
            return
        if p in ("/icon", "/apple-icon", "/apple-icon.png"):
            for cand in (ROOT / "apple-icon.png", ROOT / "icon.png"):
                if cand.is_file():
                    self._serve_path(cand)
                    return
        hit = self._map_route(p)
        if hit is not None:
            self._serve_path(hit)
            return
        super().do_GET()

    def do_POST(self):
        u = urllib.parse.urlsplit(self.path)
        p = u.path
        if self._is_stub(p):
            try:
                length = int(self.headers.get("Content-Length", 0) or 0)
            except (TypeError, ValueError):
                length = 0
            if length:
                self.rfile.read(length)
            self._send_bytes(b"", "text/plain")
            return
        if self._handle_api():
            return
        self.send_error(404)

    do_HEAD = do_GET


if __name__ == "__main__":
    port = int(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_PORT
    handler = functools.partial(Handler, directory=str(ROOT))
    with ThreadingHTTPServer(("127.0.0.1", port), handler) as srv:
        print("serving %s on http://localhost:%d" % (NAME, port), flush=True)
        srv.serve_forever()
'''

_LAUNCHER_TEMPLATE = """@echo off
rem Open __NAME__ offline clone (generated by siteclone.serve — stage 5).
cd /d "%~dp0"
start "serve___SAFE__" python "serve___SAFE__.py" __PORT__
timeout /t 2 /nobreak >nul
start "" "http://localhost:__PORT__/"
"""


def _clone_name(outdir):
    """Sanitized basename of ``outdir`` for the serve_<name>.py filename."""
    base = os.path.basename(os.path.abspath(outdir)) or "clone"
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", base).strip("._") or "clone"
    return safe


def _normalize_payloads(api_payloads):
    """JSON-round-trippable copy of ``api_payloads`` (bytes -> str)."""
    norm = {}
    for key, val in dict(api_payloads or {}).items():
        path = str(key).split("?")[0].split("#")[0]
        if not path.startswith("/"):
            path = "/" + path
        if isinstance(val, bytes):
            try:
                val = val.decode("utf-8")
            except UnicodeDecodeError:
                val = val.decode("utf-8", errors="replace")
        norm[path] = val
    # Validates JSON-serializability now so the generated file never breaks.
    json.dumps(norm, ensure_ascii=False)
    return norm


def write_server(outdir, routes, api_payloads, port=DEFAULT_PORT):
    """Write the threaded shim server ``serve_<name>.py`` into ``outdir``.

    Handles extensionless route->.html mapping, /_next/image optimizer
    mapping (incl. http-URL basename lookup), /api/* shims (captured JSON
    on GET, {} on POST), sw.js/analytics stubs, wasm/drc/glb/ktx2/webm
    MIME types and no-store cache headers. Returns the file path written.
    """
    os.makedirs(outdir, exist_ok=True)
    name = _clone_name(outdir)
    routes = [str(r) if str(r).startswith("/") else "/" + str(r)
              for r in (routes or ["/"])]
    norm = _normalize_payloads(api_payloads)
    # Double-encoded: a valid Python string literal holding the JSON doc.
    payloads_literal = json.dumps(json.dumps(norm, ensure_ascii=False))
    code = (_SERVER_TEMPLATE
            .replace("__PAYLOADS_JSON__", payloads_literal)
            .replace("__ROUTES__", json.dumps(routes))
            .replace("__PORT__", str(int(port or DEFAULT_PORT)))
            .replace("__NAME__", name))
    dest = os.path.join(os.path.abspath(outdir), "serve_%s.py" % name)
    with open(dest, "w", encoding="utf-8") as fh:
        fh.write(code)
    return dest


def write_launcher(outdir, port=DEFAULT_PORT):
    """Write ``OPEN-ME.bat`` into ``outdir``. Returns the file path written."""
    os.makedirs(outdir, exist_ok=True)
    name = _clone_name(outdir)
    bat = (_LAUNCHER_TEMPLATE
           .replace("__SAFE__", name)
           .replace("__NAME__", name)
           .replace("__PORT__", str(int(port or DEFAULT_PORT))))
    dest = os.path.join(os.path.abspath(outdir), "OPEN-ME.bat")
    with open(dest, "w", encoding="utf-8", newline="") as fh:
        fh.write(bat)
    return dest
